# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/transparencia-chile-2024',
                'doc_host': 'https://FelipeCabelloE.github.io',
                'git_url': 'https://github.com/FelipeCabelloE/transparencia-chile-2024',
                'lib_path': 'transparencia_chile_2024'},
  'syms': {'transparencia_chile_2024.core': {'transparencia_chile_2024.core.foo': ('core.html#foo', 'transparencia_chile_2024/core.py')}}}
