"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_starter.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_starter.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_starter.ipynb 4
def foo(): print("Hello there!")
